"""add installation_date, last_maintenance_date, coverage_radius_meters to cameras

Revision ID: 6fdbb853a3f9
Revises: 9712e3268387
Create Date: 2026-09-20 23:15:07.054772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdbb853a3f9'
down_revision: Union[str, Sequence[str], None] = '9712e3268387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('installation_date', sa.Date(), nullable=True))
    op.add_column('cameras', sa.Column('last_maintenance_date', sa.Date(), nullable=True))
    # server_default backfills existing rows; dropped after so the model's
    # Python-side default is what governs new inserts going forward.
    op.add_column('cameras', sa.Column('coverage_radius_meters', sa.Integer(), nullable=False, server_default='50'))
    op.alter_column('cameras', 'coverage_radius_meters', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'coverage_radius_meters')
    op.drop_column('cameras', 'last_maintenance_date')
    op.drop_column('cameras', 'installation_date')
    # ### end Alembic commands ###
