"""add snapshot_url and attributes to vehicle_events, nullable watchlist_id on alerts

Revision ID: 9712e3268387
Revises: 6dc0dabc8de2
Create Date: 2026-09-20 22:39:29.656154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9712e3268387'
down_revision: Union[str, Sequence[str], None] = '6dc0dabc8de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'watchlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('vehicle_events', sa.Column('snapshot_url', sa.String(length=255), nullable=True))
    op.add_column('vehicle_events', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_events', 'attributes')
    op.drop_column('vehicle_events', 'snapshot_url')
    op.alter_column('alerts', 'watchlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
